[package]
name = "hal-stream"
version = "0.1.15"
edition = "2021"
repository = "https://github.com/Cube-OS/hal-stream"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]