name: Release

on:
  push:
    branches:
      - main # Trigger workflow on push or pull request to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true   
    
    - name: Build and test
      run: |
        cargo build --release
        cargo test

    - name: package
      run: cargo package

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: my-package
        path: target/package/*.crate
    
    - name: create tag 
      run: |
        VERSION=$(grep "^version" Cargo.toml | cut -d' ' -f3 | tr -d '"')
        TAG_NAME="v$VERSION"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        git tag $TAG_NAME
        git push origin ${{ env.TAG_NAME }}

    - name: push
      run: git push origin ${{ env.TAG_NAME }}